<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'env' => 'get5d506000649ae923878905',
  'crypt' => 'get5d506000649f8202848761',
  'session_key' => 'get5d50600064a2d710083787',
  'MailerOptions' => 'get5d50600064a3a761102233',
  'views_path' => 'get5d50600064a55238748929',
  'Twig_Extension' => 'get5d50600064a5e718897186',
  'SubEntry5d50600064a67' => 'get5d50600064a6a313418282',
  'SubEntry5d50600064a80' => 'get5d50600064a81089979750',
  'SubEntry5d50600064a8d' => 'get5d50600064a8f947948396',
  'SubEntry5d50600064a98' => 'get5d50600064a99867763790',
  'SubEntry5d50600064aa2' => 'get5d50600064aa3545337140',
  'SubEntry5d50600064aab' => 'get5d50600064aac289493797',
  'League\\Route\\RouteCollectionInterface' => 'get5d50600064ab8873673675',
  'Core\\Render\\RendererInterface' => 'get5d50600064b2e679139110',
  'Core\\Mail\\MailerInterface' => 'get5d50600064b95017560621',
  'Core\\Log\\LogInterface' => 'get5d50600064bf3402876447',
  'Core\\session\\SessionInterface' => 'get5d50600064c50509989167',
  'Core\\Encryp\\EncryptInterface' => 'get5d50600065510733054483',
  'Core\\Validate\\ValidateInterface' => 'get5d506000657ba842264010',
  'Core\\Middleware\\pipe\\SlashesMiddleware' => 'get5d5060006580e507765284',
  'Core\\Middleware\\pipe\\RouterMiddleware' => 'get5d5060006584a386094872',
  'SubEntry5d50600065884' => 'get5d50600065888979272248',
  'Core\\Middleware\\pipe\\HttpMiddleware' => 'get5d506000658ba092227402',
  'Core\\Middleware\\pipe\\CsrfMiddleware' => 'get5d506000658e6149919641',
  'SubEntry5d5060006591d' => 'get5d50600065920806761870',
  'Core\\Middleware\\pipe\\VerifySessionMiddleware' => 'get5d50600065957374559692',
  'SubEntry5d5060006597f' => 'get5d50600065982945643858',
  'SubEntry5d50600065998' => 'get5d5060006599b992958626',
  'Core\\Middleware\\pipe\\InactivityMiddleware' => 'get5d506000659c1391204696',
  'SubEntry5d506000659e6' => 'get5d506000659e9281092084',
  'prefijo' => 'get5d50600065a12931201041',
  'App\\modules\\Auth\\AuthModule' => 'get5d50600065a26826422637',
  'SubEntry5d50600065a50' => 'get5d50600065a53495419139',
  'SubEntry5d50600065a6b' => 'get5d50600065a6d833032382',
  'SubEntry5d50600065a83' => 'get5d50600065a86349189752',
  'App\\modules\\siff\\SiffModule' => 'get5d50600065aac513821394',
  'SubEntry5d50600065ad6' => 'get5d50600065ad9639393488',
  'SubEntry5d50600065aed' => 'get5d50600065af0032278051',
  'SubEntry5d50600065b03' => 'get5d50600065b05646972488',
  'Core\\Extension\\TwigExtensionRouter' => 'get5d50600065f3e682237648',
  'SubEntry5d50600065f79' => 'get5d50600065f7c043442230',
  'Twig\\Extension\\DebugExtension' => 'get5d50600066044081306261',
  'Core\\Extension\\TwigExtensionAssets' => 'get5d506000660ee040665874',
  'Core\\Extension\\TwigExtensionMessagueFlash' => 'get5d506000661ec407477750',
  'SubEntry5d50600066216' => 'get5d5060006621a202194730',
  'Core\\Extension\\TwigExtensionSession' => 'get5d506000662d1970832727',
  'SubEntry5d506000662fb' => 'get5d506000662fe937445398',
  'Core\\Extension\\TwigExtensionCsrf' => 'get5d506000663b1143524729',
  'SubEntry5d506000663da' => 'get5d506000663dd995824237',
  'Core\\session\\FlashMessage' => 'get5d5060006643b548919098',
  'SubEntry5d50600066460' => 'get5d50600066463847628379',
);

    protected function get5d506000649ae923878905()
    {
                $value = getenv('ENV');
        if (false !== $value) return $value;
        if (!true) {
            throw new \DI\Definition\Exception\InvalidDefinition("The environment variable 'ENV' has not been defined");
        }
        return 'dev';
    }

    protected function get5d506000649f8202848761()
    {
        return [
            'secret_key' => 'af81a0fe398ab46fef0368feb147d95ffe238c56222ef4f14bcd9655e90cd880',
            'secret_iv' => 'c1738399df242358edaf0e0d5dabbfbbf999ca65cb4dd8b3a7fddd0cd2783693',
            'method' => 'AES-256-CBC',
        ];
    }

    protected function get5d50600064a2d710083787()
    {
        return '03c5f61211c9ba97eb614ccfb48b3d05d1e0d207611434d9e5d55688aedcb587';
    }

    protected function get5d50600064a3a761102233()
    {
        return [
            'host' => 'smtp.gmail.com',
            'user' => 'team.dev.sif@gmail.com',
            'pass' => 'teamdevsif2019',
            'port' => 587,
            'protocol' => 'tls',
        ];
    }

    protected function get5d50600064a55238748929()
    {
        return '/opt/lampp/htdocs/siff/resources/views/';
    }

    protected function get5d50600064a6a313418282()
    {
        return $this->delegateContainer->get('Core\\Extension\\TwigExtensionRouter');
    }

    protected function get5d50600064a81089979750()
    {
        return $this->delegateContainer->get('Twig\\Extension\\DebugExtension');
    }

    protected function get5d50600064a8f947948396()
    {
        return $this->delegateContainer->get('Core\\Extension\\TwigExtensionAssets');
    }

    protected function get5d50600064a99867763790()
    {
        return $this->delegateContainer->get('Core\\Extension\\TwigExtensionMessagueFlash');
    }

    protected function get5d50600064aa3545337140()
    {
        return $this->delegateContainer->get('Core\\Extension\\TwigExtensionSession');
    }

    protected function get5d50600064aac289493797()
    {
        return $this->delegateContainer->get('Core\\Extension\\TwigExtensionCsrf');
    }

    protected function get5d50600064a5e718897186()
    {
        return [
            0 => $this->get5d50600064a6a313418282(),
            1 => $this->get5d50600064a81089979750(),
            2 => $this->get5d50600064a8f947948396(),
            3 => $this->get5d50600064a99867763790(),
            4 => $this->get5d50600064aa3545337140(),
            5 => $this->get5d50600064aac289493797(),
        ];
    }

    protected function get5d50600064ab8873673675()
    {
        return $this->resolveFactory('Core\\Router\\RouterFactory', 'League\\Route\\RouteCollectionInterface');
    }

    protected function get5d50600064b2e679139110()
    {
        return $this->resolveFactory('Core\\Render\\RenderFactory', 'Core\\Render\\RendererInterface');
    }

    protected function get5d50600064b95017560621()
    {
        return $this->resolveFactory('Core\\Mail\\MailerFactory', 'Core\\Mail\\MailerInterface');
    }

    protected function get5d50600064bf3402876447()
    {
        return $this->resolveFactory('Core\\Log\\LogFactory', 'Core\\Log\\LogInterface');
    }

    protected function get5d50600064c50509989167()
    {
        $object = new Core\session\Session();
        return $object;
    }

    protected function get5d50600065510733054483()
    {
        return $this->resolveFactory('Core\\Encryp\\EncryptFactory', 'Core\\Encryp\\EncryptInterface');
    }

    protected function get5d506000657ba842264010()
    {
        $object = new Core\Validate\Validate();
        return $object;
    }

    protected function get5d5060006580e507765284()
    {
        $object = new Core\Middleware\pipe\SlashesMiddleware();
        return $object;
    }

    protected function get5d50600065888979272248()
    {
        return $this->delegateContainer->get('League\\Route\\RouteCollectionInterface');
    }

    protected function get5d5060006584a386094872()
    {
        $object = new Core\Middleware\pipe\RouterMiddleware($this->get5d50600065888979272248());
        return $object;
    }

    protected function get5d506000658ba092227402()
    {
        $object = new Core\Middleware\pipe\HttpMiddleware();
        return $object;
    }

    protected function get5d50600065920806761870()
    {
        return $this->delegateContainer->get('Core\\session\\SessionInterface');
    }

    protected function get5d506000658e6149919641()
    {
        $object = new Core\Middleware\pipe\CsrfMiddleware($this->get5d50600065920806761870(), '_csrf', 'csrf');
        return $object;
    }

    protected function get5d50600065982945643858()
    {
        return $this->delegateContainer->get('Core\\session\\SessionInterface');
    }

    protected function get5d5060006599b992958626()
    {
        return $this->delegateContainer->get('session_key');
    }

    protected function get5d50600065957374559692()
    {
        $object = new Core\Middleware\pipe\VerifySessionMiddleware($this->get5d50600065982945643858(), $this->get5d5060006599b992958626());
        return $object;
    }

    protected function get5d506000659e9281092084()
    {
        return $this->delegateContainer->get('Core\\session\\SessionInterface');
    }

    protected function get5d506000659c1391204696()
    {
        $object = new Core\Middleware\pipe\InactivityMiddleware($this->get5d506000659e9281092084());
        return $object;
    }

    protected function get5d50600065a12931201041()
    {
        return '/acceso';
    }

    protected function get5d50600065a53495419139()
    {
        return $this->delegateContainer->get('prefijo');
    }

    protected function get5d50600065a6d833032382()
    {
        return $this->delegateContainer->get('League\\Route\\RouteCollectionInterface');
    }

    protected function get5d50600065a86349189752()
    {
        return $this->delegateContainer->get('Core\\Mail\\MailerInterface');
    }

    protected function get5d50600065a26826422637()
    {
        $object = new App\modules\Auth\AuthModule($this->get5d50600065a53495419139(), $this->get5d50600065a6d833032382(), $this->get5d50600065a86349189752());
        return $object;
    }

    protected function get5d50600065ad9639393488()
    {
        return $this->delegateContainer->get('prefijo');
    }

    protected function get5d50600065af0032278051()
    {
        return $this->delegateContainer->get('League\\Route\\RouteCollectionInterface');
    }

    protected function get5d50600065b05646972488()
    {
        return $this->delegateContainer->get('Core\\Mail\\MailerInterface');
    }

    protected function get5d50600065aac513821394()
    {
        $object = new App\modules\siff\SiffModule($this->get5d50600065ad9639393488(), $this->get5d50600065af0032278051(), $this->get5d50600065b05646972488());
        return $object;
    }

    protected function get5d50600065f7c043442230()
    {
        return $this->delegateContainer->get('League\\Route\\RouteCollectionInterface');
    }

    protected function get5d50600065f3e682237648()
    {
        $object = new Core\Extension\TwigExtensionRouter($this->get5d50600065f7c043442230());
        return $object;
    }

    protected function get5d50600066044081306261()
    {
        $object = new Twig\Extension\DebugExtension();
        return $object;
    }

    protected function get5d506000660ee040665874()
    {
        $object = new Core\Extension\TwigExtensionAssets();
        return $object;
    }

    protected function get5d5060006621a202194730()
    {
        return $this->delegateContainer->get('Core\\session\\FlashMessage');
    }

    protected function get5d506000661ec407477750()
    {
        $object = new Core\Extension\TwigExtensionMessagueFlash($this->get5d5060006621a202194730());
        return $object;
    }

    protected function get5d506000662fe937445398()
    {
        return $this->delegateContainer->get('Core\\session\\SessionInterface');
    }

    protected function get5d506000662d1970832727()
    {
        $object = new Core\Extension\TwigExtensionSession($this->get5d506000662fe937445398());
        return $object;
    }

    protected function get5d506000663dd995824237()
    {
        return $this->delegateContainer->get('Core\\Middleware\\pipe\\CsrfMiddleware');
    }

    protected function get5d506000663b1143524729()
    {
        $object = new Core\Extension\TwigExtensionCsrf($this->get5d506000663dd995824237());
        return $object;
    }

    protected function get5d50600066463847628379()
    {
        return $this->delegateContainer->get('Core\\session\\SessionInterface');
    }

    protected function get5d5060006643b548919098()
    {
        $object = new Core\session\FlashMessage($this->get5d50600066463847628379());
        return $object;
    }

}
